export const SWITCH_TABS = 'SWITCH_TABS';
export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';